baseURL = "https://intelops.ai/"
disableLanguages = ["fr"]
disqusShortname = "themefisher-template"
googleAnalytics = ""
paginate = "6"
summaryLength = "10"
theme = "delta"
title = "Intelops"
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"
[imaging]
quality = 100
[markup.goldmark.renderer]
unsafe = true
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[module.hugoVersion]
extended = true
min = "0.84.0"
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputs]
home = ["HTML", "RSS", "WebAppManifest"]
[taxonomies]
category = "categories"
