################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[en.params]
# copyright
copyright = "Copyright @ Outfit Labs, Inc."



################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2

[fr.params]
home = "Accueil"
# copyright
copyright = "Copyright @ Outfit Labs, Inc."
