product_optimizor = []
[[footer_menu_1]]
name = "Our open source"
url = "#!"
weight = 2
[[footer_menu_1]]
name = "Contributed open source"
url = "#!"
weight = 3
[[footer_menu_3]]
name = "About"
url = "/about/"
weight = 1
[[footer_menu_3]]
name = "Contact"
url = "/contact/"
weight = 1
[[footer_menu_3]]
name = "Privacy Policy"
url = "#!"
weight = 2
[[footer_menu_3]]
name = "Terms & Conditions"
url = "#!"
weight = 3
[[footer_menu_4]]
name = "Certified"
url = "#!"
weight = 1
[[footer_menu_4]]
name = "Partner Program"
url = "#!"
weight = 2
[[footer_menu_4]]
name = "Team"
url = "/team/"
weight = 3
[[footer_menu_5]]
name = "Docs"
url = "https://docs.intelops.ai/"
weight = 1
[[footer_menu_5]]
name = "Blog"
url = "/blog/"
weight = 2
[[footer_menu_5]]
name = "Home"
url = "/"
weight = 3

[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
hasChildren = true
name = "Platform"
url = "platform/"
weight = 2
[main.params]
isMenuLarge = true

[[main]]
name = "Capten"
parent = "Platform"
url = "/capten"
weight = 1
pre = "images/icons/capten.png"
post = "<small>Convert leads and close sales deals faster.</small>"

[[main]]
name = "Compage"
parent = "Platform"
url = "/compage"
weight = 2
pre = "images/icons/optimizor.png"
post = "<small>Convert leads and close sales deals faster.</small>"

[[main]]
name = "Opty"
parent = "Platform"
url = "/opty"
weight = 2
pre = "images/icons/optimizor.png"
post = "<small>Convert leads and close sales deals faster.</small>"

[[main]]
name = "Learning Center"
url = "learning-center/"
weight = 3

[[main]]
name = "Open Source"
url = "/opensource"
weight = 10
[[main]]
name = "Our open source"
parent = "Open Source"
url = "/our-open-source"
weight = 1
[[main]]
name = "Contributed open source"
parent = "Open Source"
url = "/contributed-open-source"
weight = 2
[[main]]
name = "Blogs"
url = "blog/"
weight = 20
[[main]]
name = "Docs"
url = "https://docs.intelops.ai/"
weight = 30
[[main]]
name = "Services"
url = "services/"
weight = 40
[[main]]
hasChildren = true
name = "Resources"
url = "resources/"
weight = 50
[[main]]
name = "About"
parent = "Resources"
url = "about/"
weight = 2
[[main]]
name = "Team"
parent = "Resources"
url = "team/"
weight = 2
[[main]]
name = "Contact"
parent = "Resources"
url = "contact/"
weight = 2
[[main]]
name = "Certified"
parent = "Resources"
url = "certified/"
weight = 2
[[main]]
name = "Partner Program"
parent = "Resources"
url = "partner-program/"
weight = 2
