product_optimizor = []
[[footer_menu_1]]
name = "Our open source"
url = "#!"
weight = 2
[[footer_menu_1]]
name = "Contributed open source"
url = "#!"
weight = 3
[[footer_menu_3]]
name = "About"
url = "/about/"
weight = 1
[[footer_menu_3]]
name = "Contact"
url = "/contact/"
weight = 1
[[footer_menu_3]]
name = "Privacy Policy"
url = "#!"
weight = 2
[[footer_menu_3]]
name = "Terms & Conditions"
url = "#!"
weight = 3
[[footer_menu_4]]
name = "Certified"
url = "#!"
weight = 1
[[footer_menu_4]]
name = "Partner Program"
url = "#!"
weight = 2
[[footer_menu_4]]
name = "Team"
url = "/team/"
weight = 3
[[footer_menu_5]]
name = "Docs"
url = "https://docs.intelops.ai/"
weight = 1
[[footer_menu_5]]
name = "Blog"
url = "/blog/"
weight = 2
[[footer_menu_5]]
name = "Home"
url = "/"
weight = 3

[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
hasChildren = true
name = "Platform"
url = "platform/"
weight = 2
[main.params]
isMenuLarge = true

[[main]]
name = "Compage"
parent = "Platform"
url = "/compage"
weight = 1
pre = "images/icons/compage.svg"
post = "<small>Developers' Delight</small>"

[[main]]
name = "Capten"
parent = "Platform"
url = "/capten"
weight = 2
pre = "images/icons/capten.svg"
post = "<small>Universal Orchestrator</small>"

[[main]]
name = "QualityTrace"
parent = "Platform"
url = "/quality-trace"
weight = 3
pre = "images/icons/quality-trace.svg"
post = "<small>Tracing Based Testing</small>"

[[main]]
name = "Opty"
parent = "Platform"
url = "/opty"
weight = 4
pre = "images/icons/opty.svg"
post = "<small>Optimize What You Want</small>"

[[main]]
name = "KubViz"
parent = "Platform"
url = "/kubviz"
weight = 5
pre = "images/icons/kubviz.svg"
post = "<small>Observability for Ops & SREs</small>"

[[main]]
name = "Tarian"
parent = "Platform"
url = "/tarian"
weight = 6
pre = "images/icons/tarian.svg"
post = "<small>Run Time Protection for K8s</small>"

[[main]]
name = "Learning Center"
url = "learning-center/"
weight = 3

# [[main]]
# name = "Open Source"
# url = "/opensource"
# weight = 10
# [main.params]
# isMenuLarge = true

# [[main]]
# name = "Our open source"
# parent = "Open Source"
# url = "/our-open-source"
# weight = 1
# pre = "images/icons/opensource.png"
# post = "<small>Convert leads and close sales deals faster.</small>"

# [[main]]
# name = "Contributed open source"
# parent = "Open Source"
# url = "/contributed-open-source"
# weight = 2
# pre = "images/icons/opensource.png"
# post = "<small>Convert leads and close sales deals faster.</small>"

[[main]]
name = "Blogs"
url = "blog/"
weight = 20

[[main]]
name = "Docs"
url = "https://docs.intelops.ai/"
weight = 30

[[main]]
name = "Services"
url = "/services-form"
weight = 40
[main.params]
isMenuLarge = true
parent= "Services"
[[main]]
name = "Custom Services"
parent = "Services"
url = "/services-form"
weight = 1
pre = "images/icons/opensource.png"
post = "<small>Cloud Native Development Services, and SRE, DevSecOps & Platform Engineering Services</small>"


[[main]]
hasChildren = true
name = "Resources"
url = "resources/"
weight = 50
[[main]]
name = "About"
parent = "Resources"
url = "about/"
weight = 2
# [[main]]
# name = "Team"
# parent = "Resources"
# url = "team/"
# weight = 2
[[main]]
name = "Contact"
parent = "Resources"
url = "contact/"
weight = 2
# [[main]]
# name = "Certified"
# parent = "Resources"
# url = "certified/"
# weight = 2
# [[main]]
# name = "Partner Program"
# parent = "Resources"
# url = "partner-program/"
# weight = 2
