address = "9567 Turner Trace Apt. BC C3G8A4"
author = "Intelops"
career_form_action = "#!"
contact_form_action = "#!"
custom_script = ""
description = "Next-Gen Ai based solution to democratize cloud native, software supply chain security, quality engineering, Kubernetes and security using Kernel technology like eBPF and Machine Learning. Empower Engineers to easily adopt concepts like cloud-native, webassembly, chaos engineering, detection engineering, security chaos engineering, gitops, self service, platform engineering, etc. Imagination is your limit!"
email = "info@email.com"
favicon = "images/favicon/favicon-32x32.png"
image = "images/logo.png"

logo = "images/logos/logo-dark.svg"
logo_light = "images/logos/logo-light.svg"
logo_dark = "images/logos/logo-dark.svg"
footer_logo_dark = false
logo_webp = false

logo_text = "Intelops"
logo_width = "130px"
mainSections = ["blog"]
mobile = "+211234565523"
fullSiteSearch = true

# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "GTM-PVRN5BQ" # example: G-XXXXXXXXXX

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Intelops", "Cloud-Native", "Ai", "DevOps", "SRE", "Kubernetes", "Talent", "Democratize", "Next-Gen"]
description = "DevSecOps concept in development and testing"
author = "Intelops"
image = "images/og-image.jpg" # this image will be used as fallback if a page has no image of its own

[footer]
footer_light = false
# bg_color = "#1e384c"
# bg_image = "images/bg-banner-page.jpg"
bg_image_overlay_color = "rgba(0,0,0,.65)"
[call_to_action]
button_label = "Contact Us"
button_link = "contact/"
enable = true
image = "images/footer/homepage/contact-image.svg"
subtitle = "We heard the pain of building the Talent, keeping up with Concepts, Culture, Technology and Tools. We have been there! Hence, we built the new Ai-based automated solution to solve the problems for everyone."
title = "Looking for efficient and optimized Cloud-Native implementation? <br> Let us make your life easy!"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[navigation_button]
enable = true
icon = "far fa-user"
label = "Log In"
link = "#!"
[navigation_button_two]
enable = true
label = "Sign Up Now"
link = "#!"
[preloader]
enable = false
preloader = "images/loader.png"

[newsletter]
enable = true
clickup_iframe_url = "https://forms.clickup.com/9006002197/f/8cctc0n-7520/VCGTBDZHNQ41SR6Y97"
button_label = "Subscribe for Newsletter"

[blog_popup]
enable = true
clickup_iframe_url = "https://forms.clickup.com/9006002197/f/8cctc0n-7510/JF9T5CQC8LRFXTUBND"

[learning_center_popup]
enable = true
clickup_iframe_url = "https://forms.clickup.com/9006002197/f/8cctc0n-7510/JF9T5CQC8LRFXTUBND"

[[social]]
icon = "fab fa-facebook"
link = "#!"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "#!"
title = "twitter"
[[social]]
icon = "fab fa-instagram"
link = "#!"
title = "instagram"
[[social]]
icon = "fab fa-github"
link = "#!"
title = "github"
[[social]]
icon = "fab fa-linkedin"
link = "#!"
title = "linkedin"