############# English navigation ##############

# main menu
[[main]]
weight = 1
name = "Home"
hasChildren = true

  [[main]]
  parent = "Home"
  name = "Home 1"
  url = "/"
  weight = 1

  [[main]]
  parent = "Home"
  name = "Home 2"
  url = "home-2/"
  weight = 2

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "How It Works"
url = "how-it-works/"
weight = 4

[[main]]
name = "Blog"
url = "blog/"
weight = 5

[[main]]
weight = 7
name = "Pages"
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Pricing"
  url = "pricing/"
  weight = 7

  [[main]]
  parent = "Pages"
  name = "Team"
  url = "team/"
  weight = 11

  [[main]]
  parent = "Pages"
  name = "Career"
  url = "career/"
  weight = 13

  [[main]]
  parent = "Pages"
  name = "Career Single"
  url = "career/digital-marketing-paid-media-manager/"
  weight = 15

  [[main]]
  parent = "Pages"
  name = "Blog Details"
  url = "blog/post-5/"
  weight = 17

  [[main]]
  parent = "Pages"
  name = "Author Single"
  url = "author/awab-husameldin/"
  weight = 18
  
[[main]]
name = "Contact"
url = "contact/"
weight = 8



### footer menus
# footer_menu_1
[[footer_menu_1]]
name = "Product 01"
url = "#!"
weight = 1

[[footer_menu_1]]
name = "Example Product 02"
url = "#!"
weight = 2

[[footer_menu_1]]
name = "Example Product 03"
url = "#!"
weight = 3

[[footer_menu_1]]
name = "Example Product 04"
url = "#!"
weight = 4


# footer_menu_2
[[footer_menu_2]]
name = "Logo & Branding"
url = "#!"
weight = 1

[[footer_menu_2]]
name = "Pay-Per-Click"
url = "#!"
weight = 2

[[footer_menu_2]]
name = "Website Design"
url = "#!"
weight = 3

[[footer_menu_2]]
name = "App Design"
url = "#!"
weight = 4

[[footer_menu_2]]
name = "SEO Optimization"
url = "#!"
weight = 5


# footer_menu_3
[[footer_menu_3]]
name = "Contact"
url = "contact/"
weight = 1

[[footer_menu_3]]
name = "Privacy Policy"
url = "#!"
weight = 2

[[footer_menu_3]]
name = "Terms & Conditions"
url = "#!"
weight = 3


# footer_menu_4
[[footer_menu_4]]
name = "How It Works"
url = "#!"
weight = 1

[[footer_menu_4]]
name = "Features"
url = "#!"
weight = 2

[[footer_menu_4]]
name = "Pricing 1"
url = "pricing-1/"
weight = 3

[[footer_menu_4]]
name = "Pricing 2"
url = "#!"
weight = 4


# footer_menu_5
[[footer_menu_5]]
name = "Author"
url = "author/awab-husameldin/"
weight = 1

[[footer_menu_5]]
name = "Blog"
url = "blog/"
weight = 2

[[footer_menu_5]]
name = "Blog Details"
url = "blog/post-1/"
weight = 3

[[footer_menu_5]]
name = "Career"
url = "career/"
weight = 4

[[footer_menu_5]]
name = "Career Single"
url = "career/digital-marketing-paid-media-manager/"
weight = 5